plugins {
    id 'com.android.application'
}

android {
    namespace 'com.viralenunclick.cambiosfintech'
    compileSdk 36

    defaultConfig {
        applicationId "com.viralenunclick.cambiosfintech"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            applicationIdSuffix ""
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
